name = "mcp-workflowy-remote"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

main = "dist/worker.js"

# Default configuration (production)
vars = { ENVIRONMENT = "production", DEBUG = "false" }

# Preview versions use the same worker configuration
# Cloudflare automatically generates unique preview URLs with version IDs
# Format: https://<version-id>-mcp-workflowy-remote.<subdomain>.workers.dev
# Use: wrangler versions upload --tag <tag-name>

# For private environment variables like API keys, use:
# wrangler secret put ALLOWED_API_KEYS
# wrangler secret put WORKFLOWY_USERNAME  # Optional: fallback username
# wrangler secret put WORKFLOWY_PASSWORD  # Optional: fallback password