name = "mcp-workflowy-remote"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

main = "dist/worker.js"

# Default configuration (production)
vars = { ENVIRONMENT = "production", DEBUG = "false" }

# KV Namespaces for OAuth storage
# Note: KV storage will be configured dynamically during deployment
# OAuth will work with or without KV storage (credentials are passed in OAuth flow)
# kv_namespaces = [
#   { binding = "OAUTH_KV", id = "oauth-kv-namespace-id", preview_id = "oauth-kv-preview-id" }
# ]

# Observability configuration for comprehensive logging
# Note: logpush requires Enterprise plan, using basic observability instead
[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1.0  # Log 100% of requests (adjust for high-traffic scenarios)

# Preview versions use the same worker configuration
# Cloudflare automatically generates unique preview URLs with version IDs
# Format: https://<version-id>-mcp-workflowy-remote.<subdomain>.workers.dev
# Use: wrangler versions upload --tag <tag-name>

# For private environment variables like API keys, use:
# wrangler secret put ALLOWED_API_KEYS
# wrangler secret put WORKFLOWY_USERNAME  # Optional: fallback username
# wrangler secret put WORKFLOWY_PASSWORD  # Optional: fallback password