name = "mcp-workflowy-remote"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

main = "dist/worker.js"

# Default configuration (production)
vars = { ENVIRONMENT = "production", DEBUG = "false" }

# Preview environment
[env.preview]
name = "mcp-workflowy-remote-preview"
vars = { ENVIRONMENT = "preview", DEBUG = "true" }

# For private environment variables like API keys, use:
# Production: wrangler secret put ALLOWED_API_KEYS
# Preview: wrangler secret put ALLOWED_API_KEYS --env preview
# wrangler secret put WORKFLOWY_USERNAME [--env preview]  # Optional: fallback Workflowy username  
# wrangler secret put WORKFLOWY_PASSWORD [--env preview]  # Optional: fallback Workflowy password