name = "mcp-workflowy-remote"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

main = "dist/worker.js"

# Default configuration (production)
vars = { ENVIRONMENT = "production", DEBUG = "false" }

# KV Namespaces for OAuth storage
kv_namespaces = [
  { binding = "OAUTH_KV", id = "9f4ddde0570a4527b0318ee774e26d19", preview_id = "be7a48b639de41608d766a8ddcb7bdc6" }
]

# Observability configuration for comprehensive logging
# Note: logpush requires Enterprise plan, using basic observability instead
[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1.0  # Log 100% of requests (adjust for high-traffic scenarios)

# Preview versions use the same worker configuration
# Cloudflare automatically generates unique preview URLs with version IDs
# Format: https://<version-id>-mcp-workflowy-remote.<subdomain>.workers.dev
# Use: wrangler versions upload --tag <tag-name>

# For private environment variables like API keys, use:
# wrangler secret put ALLOWED_API_KEYS
# Note: WORKFLOWY_USERNAME/WORKFLOWY_PASSWORD not needed - worker uses OIDC authentication