name: Build, Version, and Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main        # Deploy to production
      - preview     # Deploy to preview
  pull_request:
    branches:
      - main        # Create preview for PRs to main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
    name: Semantic Versioning
    
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      released: ${{ steps.semantic.outputs.new_release_published }}
      release-notes: ${{ steps.semantic.outputs.new_release_notes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build project
        run: |
          npm run build
          npm run build:worker

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    needs: [version]
    if: always() && github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Deploy to Production
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build Worker
        run: npm run build:worker

      - name: Upload secrets and deploy to Production
        id: deploy
        run: |
          # Upload secrets to production environment (default)
          echo "🔑 Uploading secrets to production..."
          echo "ALLOWED_API_KEYS = $ALLOWED_API_KEYS" | npx wrangler secret bulk
          
          # Deploy to production
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          echo "🚀 Deploying v$VERSION to production..."
          DEPLOY_OUTPUT=$(npx wrangler deploy 2>&1)
          echo "$DEPLOY_OUTPUT"
          
          # Extract worker URL
          WORKER_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[a-zA-Z0-9.-]*\.workers\.dev' | head -1)
          echo "worker-url=$WORKER_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployed to production: $WORKER_URL"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALLOWED_API_KEYS: ${{ secrets.ALLOWED_API_KEYS }}

      - name: Verify production deployment
        run: |
          WORKER_URL="${{ steps.deploy.outputs.worker-url }}"
          
          if [ -z "$WORKER_URL" ]; then
            echo "❌ Failed to capture worker URL"
            exit 1
          fi
          
          # Extract first API key for testing
          FIRST_API_KEY=$(echo "$ALLOWED_API_KEYS" | cut -d',' -f1)
          
          echo "🧪 Verifying production deployment at: $WORKER_URL"
          echo "🔑 Using API key for testing: ${FIRST_API_KEY:0:10}..."
          
          # Wait for deployment to propagate
          sleep 30
          
          # Test health endpoint
          echo "Testing health endpoint..."
          HEALTH_RESPONSE=$(curl -f "$WORKER_URL/health" 2>/dev/null) || (echo "❌ Health check failed" && exit 1)
          echo "✅ Health check passed: $HEALTH_RESPONSE"
          
          # Test root endpoint and verify environment
          echo "Testing root endpoint..."
          ROOT_RESPONSE=$(curl -s "$WORKER_URL/")
          ENVIRONMENT=$(echo "$ROOT_RESPONSE" | jq -r '.environment // "unknown"')
          
          if [ "$ENVIRONMENT" = "production" ]; then
            echo "✅ Environment confirmed: $ENVIRONMENT"
          else
            echo "⚠️  Environment mismatch - expected: production, got: $ENVIRONMENT"
          fi
          
          # Full test suite for production
          echo "Testing tools endpoint..."
          TOOLS_COUNT=$(curl -f "$WORKER_URL/tools" -H "Authorization: Bearer $FIRST_API_KEY" 2>/dev/null | jq '.tools | length') || (echo "❌ Tools endpoint failed" && exit 1)
          if [ "$TOOLS_COUNT" -gt 0 ]; then
            echo "✅ Tools endpoint passed - $TOOLS_COUNT tools available"
          else
            echo "❌ Tools endpoint failed - no tools found"
            exit 1
          fi
          
          # Test MCP endpoint
          echo "Testing MCP endpoint..."
          AUTH_SUCCESS=$(curl -s -X POST "$WORKER_URL/mcp" \
            -H "Authorization: Bearer $FIRST_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}')
          
          if echo "$AUTH_SUCCESS" | grep -q -E "(result|tools|jsonrpc)"; then
            echo "✅ MCP endpoint working"
          else
            echo "❌ MCP endpoint failed"
            exit 1
          fi
          
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          RELEASED="${{ needs.version.outputs.released }}"
          
          echo "🎉 All deployment verification tests passed!"
          
          if [ "$RELEASED" = "true" ]; then
            echo "📦 New version v$VERSION released and deployed!"
            echo "📝 Release notes: ${{ needs.version.outputs.release-notes }}"
          else
            echo "🔄 Version v$VERSION deployed to production"
          fi
          
          echo "🚀 Production server ready at: $WORKER_URL"
        env:
          ALLOWED_API_KEYS: ${{ secrets.ALLOWED_API_KEYS }}

  deploy-preview:
    if: github.ref == 'refs/heads/preview' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Create Preview Version
    environment: preview

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build Worker
        run: npm run build:worker

      - name: Create Preview Version
        id: deploy-preview
        run: |
          # Create version tag for organization in Cloudflare dashboard
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            VERSION_TAG="pr${{ github.event.number }}"
            echo "🚀 Creating preview version for PR #${{ github.event.number }}"
          else
            VERSION_TAG="preview"
            echo "🚀 Creating preview version for preview branch"
          fi
          
          # Upload new version with persistent preview alias
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, create both version-specific and pr alias
            DEPLOY_OUTPUT=$(npx wrangler versions upload --tag "$VERSION_TAG" --preview-alias "pr${{ github.event.number }}" --message "Preview: PR #${{ github.event.number }}" 2>&1)
          else
            # For preview branch, always update the "preview" alias
            DEPLOY_OUTPUT=$(npx wrangler versions upload --tag "$VERSION_TAG" --preview-alias "preview" --message "Preview: Phase 0 Critical Operations" 2>&1)
          fi
          echo "$DEPLOY_OUTPUT"
          
          # Extract version ID and preview URLs from wrangler output
          VERSION_ID=$(echo "$DEPLOY_OUTPUT" | grep -o 'Version ID: [a-f0-9-]*' | cut -d' ' -f3)
          VERSION_PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'Version Preview URL: https://[^[:space:]]*' | cut -d' ' -f4)
          ALIAS_PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'Alias Preview URL: https://[^[:space:]]*' | cut -d' ' -f4)
          
          # Use alias URL as primary preview URL, fall back to version URL
          if [ -n "$ALIAS_PREVIEW_URL" ]; then
            PREVIEW_URL="$ALIAS_PREVIEW_URL"
          else
            PREVIEW_URL="$VERSION_PREVIEW_URL"
          fi
          
          echo "version-id=$VERSION_ID" >> $GITHUB_OUTPUT
          echo "preview-url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "version-preview-url=$VERSION_PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "alias-preview-url=$ALIAS_PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "version-tag=$VERSION_TAG" >> $GITHUB_OUTPUT
          
          echo "✅ Preview version created: $VERSION_TAG"
          echo "📝 Version ID: $VERSION_ID"
          if [ -n "$ALIAS_PREVIEW_URL" ]; then
            echo "🔗 Persistent Alias URL: $ALIAS_PREVIEW_URL"
            echo "🔗 Version-specific URL: $VERSION_PREVIEW_URL"
          else
            echo "🔗 Preview URL: $PREVIEW_URL"
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Verify preview version
        run: |
          PREVIEW_URL="${{ steps.deploy-preview.outputs.preview-url }}"
          ALIAS_URL="${{ steps.deploy-preview.outputs.alias-preview-url }}"
          VERSION_URL="${{ steps.deploy-preview.outputs.version-preview-url }}"
          VERSION_ID="${{ steps.deploy-preview.outputs.version-id }}"
          VERSION_TAG="${{ steps.deploy-preview.outputs.version-tag }}"
          
          if [ -z "$PREVIEW_URL" ]; then
            echo "❌ Failed to capture preview URL"
            exit 1
          fi
          
          # Use production API keys since it's the same worker, just a different version
          FIRST_API_KEY=$(echo "$ALLOWED_API_KEYS" | cut -d',' -f1)
          
          echo "🧪 Verifying preview version: $VERSION_TAG"
          echo "📝 Version ID: $VERSION_ID"
          if [ -n "$ALIAS_URL" ]; then
            echo "🔗 Persistent Alias: $ALIAS_URL"
            echo "🔗 Version-specific: $VERSION_URL"
          else
            echo "🔗 Preview URL: $PREVIEW_URL"
          fi
          
          # Wait for version to propagate
          sleep 25
          
          # Test health endpoint
          echo "Testing health endpoint..."
          HEALTH_RESPONSE=$(curl -f "$PREVIEW_URL/health" 2>/dev/null) || (echo "❌ Health check failed" && exit 1)
          echo "✅ Health check passed: $HEALTH_RESPONSE"
          
          # Test basic functionality
          echo "Testing basic authentication..."
          AUTH_TEST=$(curl -s "$PREVIEW_URL/tools" -H "Authorization: Bearer $FIRST_API_KEY")
          if echo "$AUTH_TEST" | grep -q "tools"; then
            echo "✅ Preview version working"
          else
            echo "❌ Preview version failed"
            exit 1
          fi
          
          echo "🎉 Preview version verification passed!"
          if [ -n "$ALIAS_URL" ]; then
            echo "🔗 Stable Preview URL: $ALIAS_URL"
            echo "🔗 Version-specific URL: $VERSION_URL"
            echo "📦 Version: $VERSION_TAG ($VERSION_ID)"
            echo ""
            echo "ℹ️  The 'preview' alias always points to the latest preview branch."
            echo "ℹ️  Production remains unchanged until merged to main."
          else
            echo "🔗 Preview URL: $PREVIEW_URL"
            echo "📦 Version: $VERSION_TAG ($VERSION_ID)"
          fi
        env:
          ALLOWED_API_KEYS: ${{ secrets.ALLOWED_API_KEYS }}