name: Build, Version, and Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main        # Deploy to production
      - preview     # Deploy to preview
  pull_request:
    branches:
      - main        # Create preview for PRs to main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
    name: Semantic Versioning
    
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      released: ${{ steps.semantic.outputs.new_release_published }}
      release-notes: ${{ steps.semantic.outputs.new_release_notes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build project
        run: |
          npm run build
          npm run build:worker

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [version]
    if: always() && (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Deploy MCP Workflowy Server
    
    strategy:
      matrix:
        include:
          - environment: production
            condition: github.ref == 'refs/heads/main'
            wrangler_env: ""
            api_key_secret: ALLOWED_API_KEYS
            github_env: production
            sleep_time: 30
          - environment: preview  
            condition: github.ref == 'refs/heads/preview' || github.event_name == 'pull_request'
            wrangler_env: "--env preview"
            api_key_secret: ALLOWED_API_KEYS_PREVIEW
            github_env: preview
            sleep_time: 15
    
    environment: ${{ matrix.github_env }}
    if: ${{ matrix.condition }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build Worker
        run: npm run build:worker

      - name: Upload secrets and deploy
        id: deploy
        run: |
          # Upload secrets to environment
          echo "🔑 Uploading secrets to ${{ matrix.environment }}..."
          if [ "${{ matrix.wrangler_env }}" = "" ]; then
            echo "ALLOWED_API_KEYS = $API_KEYS" | npx wrangler secret bulk
          else
            echo "ALLOWED_API_KEYS = $API_KEYS" | npx wrangler secret bulk ${{ matrix.wrangler_env }}
          fi
          
          # Deploy
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "🚀 Deploying PR #${{ github.event.number }} to ${{ matrix.environment }}"
          else
            echo "🚀 Deploying v$VERSION to ${{ matrix.environment }}"
          fi
          
          if [ "${{ matrix.wrangler_env }}" = "" ]; then
            DEPLOY_OUTPUT=$(npx wrangler deploy 2>&1)
          else
            DEPLOY_OUTPUT=$(npx wrangler deploy ${{ matrix.wrangler_env }} 2>&1)
          fi
          
          echo "$DEPLOY_OUTPUT"
          
          # Extract worker URL
          WORKER_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[a-zA-Z0-9.-]*\.workers\.dev' | head -1)
          echo "worker-url=$WORKER_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployed to ${{ matrix.environment }}: $WORKER_URL"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          API_KEYS: ${{ secrets[matrix.api_key_secret] }}

      - name: Verify deployment
        run: |
          WORKER_URL="${{ steps.deploy.outputs.worker-url }}"
          
          if [ -z "$WORKER_URL" ]; then
            echo "❌ Failed to capture worker URL"
            exit 1
          fi
          
          # Extract first API key for testing
          FIRST_API_KEY=$(echo "$API_KEYS" | cut -d',' -f1)
          
          echo "🧪 Verifying ${{ matrix.environment }} deployment at: $WORKER_URL"
          echo "🔑 Using API key for testing: ${FIRST_API_KEY:0:10}..."
          
          # Wait for deployment to propagate
          sleep ${{ matrix.sleep_time }}
          
          # Test health endpoint
          echo "Testing health endpoint..."
          HEALTH_RESPONSE=$(curl -f "$WORKER_URL/health" 2>/dev/null) || (echo "❌ Health check failed" && exit 1)
          echo "✅ Health check passed: $HEALTH_RESPONSE"
          
          # Test root endpoint and verify environment
          echo "Testing root endpoint..."
          ROOT_RESPONSE=$(curl -s "$WORKER_URL/")
          ENVIRONMENT=$(echo "$ROOT_RESPONSE" | jq -r '.environment // "unknown"')
          
          if [ "$ENVIRONMENT" = "${{ matrix.environment }}" ]; then
            echo "✅ Environment confirmed: $ENVIRONMENT"
          else
            echo "⚠️  Environment mismatch - expected: ${{ matrix.environment }}, got: $ENVIRONMENT"
          fi
          
          # Test authentication (production gets full test suite, preview gets basic test)
          if [ "${{ matrix.environment }}" = "production" ]; then
            # Full test suite for production
            echo "Testing tools endpoint..."
            TOOLS_COUNT=$(curl -f "$WORKER_URL/tools" -H "Authorization: Bearer $FIRST_API_KEY" 2>/dev/null | jq '.tools | length') || (echo "❌ Tools endpoint failed" && exit 1)
            if [ "$TOOLS_COUNT" -gt 0 ]; then
              echo "✅ Tools endpoint passed - $TOOLS_COUNT tools available"
            else
              echo "❌ Tools endpoint failed - no tools found"
              exit 1
            fi
            
            # Test MCP endpoint
            echo "Testing MCP endpoint..."
            AUTH_SUCCESS=$(curl -s -X POST "$WORKER_URL/mcp" \
              -H "Authorization: Bearer $FIRST_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}')
            
            if echo "$AUTH_SUCCESS" | grep -q -E "(result|tools|jsonrpc)"; then
              echo "✅ MCP endpoint working"
            else
              echo "❌ MCP endpoint failed"
              exit 1
            fi
          else
            # Basic test for preview
            echo "Testing basic authentication..."
            AUTH_TEST=$(curl -s "$WORKER_URL/tools" -H "Authorization: Bearer $FIRST_API_KEY")
            if echo "$AUTH_TEST" | grep -q "tools"; then
              echo "✅ Preview authentication working"
            else
              echo "❌ Preview authentication failed"
              exit 1
            fi
          fi
          
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          RELEASED="${{ needs.version.outputs.released }}"
          
          echo "🎉 All deployment verification tests passed!"
          
          if [ "${{ matrix.environment }}" = "production" ] && [ "$RELEASED" = "true" ]; then
            echo "📦 New version v$VERSION released and deployed!"
            echo "📝 Release notes: ${{ needs.version.outputs.release-notes }}"
          else
            echo "🔄 Version v$VERSION deployed to ${{ matrix.environment }}"
          fi
          
          echo "🚀 ${{ matrix.environment }} server ready at: $WORKER_URL"
        env:
          API_KEYS: ${{ secrets[matrix.api_key_secret] }}