name: Build, Version, and Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
    name: Semantic Versioning
    
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      released: ${{ steps.semantic.outputs.new_release_published }}
      release-notes: ${{ steps.semantic.outputs.new_release_notes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests configured"
        continue-on-error: true

      - name: Build project
        run: |
          npm run build
          npm run build:worker

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [version]
    if: always() && (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Deploy Workflowy MCP Server

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Worker
        run: npm run build:worker

      - name: Upload secrets and deploy to Cloudflare Workers
        id: deploy
        run: |
          # First, upload the secrets to production environment
          echo "🔑 Uploading secrets..."
          echo "ALLOWED_API_KEYS = $ALLOWED_API_KEYS" | npx wrangler secret bulk --env production
          
          # Then deploy and capture output
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          echo "🚀 Deploying worker v$VERSION..."
          DEPLOY_OUTPUT=$(npx wrangler deploy --env production 2>&1)
          echo "$DEPLOY_OUTPUT"
          
          # Extract the worker URL from the output
          WORKER_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[a-zA-Z0-9.-]*\.workers\.dev' | head -1)
          
          # Set as output for next step
          echo "worker-url=$WORKER_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployed v$VERSION to: $WORKER_URL"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALLOWED_API_KEYS: ${{ secrets.ALLOWED_API_KEYS }}

      - name: Verify deployment
        run: |
          # Get the worker URL from the previous step
          WORKER_URL="${{ steps.deploy.outputs.worker-url }}"
          
          if [ -z "$WORKER_URL" ]; then
            echo "❌ Failed to capture worker URL from deployment step"
            exit 1
          fi
          
          # Extract first API key from comma-separated list for testing
          FIRST_API_KEY=$(echo "$ALLOWED_API_KEYS" | cut -d',' -f1)
          
          if [ -z "$FIRST_API_KEY" ]; then
            echo "❌ No API key available for testing"
            exit 1
          fi
          
          echo "🧪 Verifying deployment at: $WORKER_URL"
          echo "🔑 Using first API key for testing: ${FIRST_API_KEY:0:10}..."
          
          # Wait a moment for deployment to propagate
          sleep 30
          
          # Test health endpoint (no auth required)
          echo "Testing health endpoint..."
          HEALTH_RESPONSE=$(curl -f "$WORKER_URL/health" 2>/dev/null) || (echo "❌ Health check failed" && exit 1)
          echo "✅ Health check passed: $HEALTH_RESPONSE"
          
          # Test root endpoint (no auth required)
          echo "Testing root endpoint..."
          ROOT_NAME=$(curl -f "$WORKER_URL/" 2>/dev/null | jq -r .name) || (echo "❌ Root endpoint failed" && exit 1)
          echo "✅ Root endpoint passed: $ROOT_NAME"
          
          # Test tools listing (with auth required)
          echo "Testing tools endpoint..."
          TOOLS_COUNT=$(curl -f "$WORKER_URL/tools" -H "Authorization: Bearer $FIRST_API_KEY" 2>/dev/null | jq '.tools | length') || (echo "❌ Tools endpoint failed" && exit 1)
          if [ "$TOOLS_COUNT" -gt 0 ]; then
            echo "✅ Tools endpoint passed - $TOOLS_COUNT tools available"
          else
            echo "❌ Tools endpoint failed - no tools found"
            exit 1
          fi
          
          # Test authentication requirement (should fail without API key)
          echo "Testing authentication requirement without API key..."
          AUTH_RESPONSE=$(curl -s -X POST "$WORKER_URL/mcp" -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}}')
          if echo "$AUTH_RESPONSE" | grep -q "Unauthorized"; then
            echo "✅ Authentication requirement working - unauthorized requests properly blocked"
          else
            echo "❌ Authentication bypass detected - this should not happen!"
            echo "Response: $AUTH_RESPONSE"
            exit 1
          fi
          
          # Test authenticated request (should succeed with API key)
          echo "Testing authenticated request with valid API key..."
          AUTH_SUCCESS=$(curl -s -X POST "$WORKER_URL/mcp" \
            -H "Authorization: Bearer $FIRST_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}')
          
          # Should get a valid JSON-RPC response with tools list
          if echo "$AUTH_SUCCESS" | grep -q -E "(result|tools|jsonrpc)"; then
            echo "✅ API key authentication working - request processed"
            echo "Response preview: $(echo "$AUTH_SUCCESS" | head -c 200)..."
          else
            echo "❌ API key authentication failed"
            echo "Response: $AUTH_SUCCESS"
            exit 1
          fi
          
          # Test SSE endpoint availability (should require auth)
          echo "Testing SSE endpoint..."
          SSE_RESPONSE=$(curl -s -X POST "$WORKER_URL/sse" \
            -H "Accept: text/event-stream" \
            -H "Content-Type: application/json" \
            -d '{}')
          
          if echo "$SSE_RESPONSE" | grep -q "Unauthorized"; then
            echo "✅ SSE endpoint properly protected with authentication"
          else
            echo "⚠️  SSE endpoint response: $(echo "$SSE_RESPONSE" | head -c 100)..."
          fi
          
          # Test new server info endpoint with environment details
          echo "Testing enhanced server info..."
          SERVER_RESPONSE=$(curl -s "$WORKER_URL/")
          ENVIRONMENT=$(echo "$SERVER_RESPONSE" | jq -r '.environment // "unknown"')
          FEATURES=$(echo "$SERVER_RESPONSE" | jq -r '.features // [] | join(", ")')
          
          echo "Server environment: $ENVIRONMENT"
          echo "Server features: $FEATURES"
          
          if echo "$SERVER_RESPONSE" | grep -q -E "(environment|features|security)"; then
            echo "✅ Enhanced server info working - environment: $ENVIRONMENT"
          else
            echo "⚠️  Server info response: $SERVER_RESPONSE"
          fi
          
          VERSION="${{ needs.version.outputs.version || 'dev' }}"
          RELEASED="${{ needs.version.outputs.released }}"
          
          echo "🎉 All deployment verification tests passed!"
          
          if [ "$RELEASED" == "true" ]; then
            echo "📦 New version v$VERSION released and deployed!"
            echo "📝 Release notes: ${{ needs.version.outputs.release-notes }}"
          else
            echo "🔄 Development version v$VERSION deployed for testing"
          fi
          
          echo "🚀 Your secure remote MCP server is ready at: $WORKER_URL"
          echo "🔑 Use your API keys to authenticate MCP client requests"
        env:
          ALLOWED_API_KEYS: ${{ secrets.ALLOWED_API_KEYS }}